trigger:
- none
 
variables:
  IISWebApiName: 'dotnet-web-api'
 
resources:
  pipelines:
  - pipeline: buildPipeline
    project: dotnet-web-api
    source: dotnet-web-api-build
    branch: 'main'

stages:
  - stage: DeployApi
    displayName: 'Deploy Api'       
    pool:
      vmImage: windows-latest
     
    jobs:   
    - deployment: DeployApi
      displayName: 'Deploy Api'
      environment: 'Windows Server.vmwin-tf-az-iis'
      strategy:
       runOnce:
         deploy:          
          steps:
          - checkout: none
           
          - download: buildPipeline
            name: DownloadBuildArtifacts             
            displayName: 'Download build artifacts'
            artifact: dotnet-web-api
                     
          - task: IISWebAppManagementOnMachineGroup@0
            name: 'StopIIS'
            displayName: 'Stop IIS Web Api - ${{ variables.IISWebApiName }}'
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              StartStopWebsiteName: '${{ variables.IISWebApiName }}'         
                           
          - task: IISWebAppDeploymentOnMachineGroup@0
            name: 'DeployIIS'
            displayName: 'Deploy IIS Web API - ${{ variables.IISWebApiName }}'         
            inputs:
              WebSiteName: '${{ variables.IISWebApiName }}'             
              Package: '$(Pipeline.Workspace)\buildPipeline\dotnet-web-api\s'
              TakeAppOfflineFlag: false
           
          - task: IISWebAppManagementOnMachineGroup@0
            name: 'StartIIS'
            displayName: 'Start IIS Web Api - ${{ variables.IISWebApiName }}'               
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: '${{ variables.IISWebApiName }}'